#!/bin/bash

# Complete Deployment Script for Bedrock Agent Test Bed with Knowledge Base
# This script automates the entire deployment process using Terraform-managed S3
# 
# Usage:
#   ./deploy-complete.sh           # Deploy without prefix
#   ./deploy-complete.sh jd        # Deploy with 'jd' prefix
#   ./deploy-complete.sh dev       # Deploy with 'dev' prefix

set -e

# Parse arguments
PREFIX=""
if [ $# -eq 1 ]; then
    PREFIX="$1"
    # Validate prefix format
    if [[ ! $PREFIX =~ ^[a-z0-9]{1,3}$ ]]; then
        echo "❌ Invalid prefix format. Must be 1-3 lowercase alphanumeric characters."
        echo "   Examples: 'jd', 'dev', 'sm1'"
        exit 1
    fi
    echo "🏷️  Using prefix: $PREFIX"
elif [ $# -gt 1 ]; then
    echo "❌ Too many arguments. Expected 0 or 1 argument."
    echo "   Usage: $0 [PREFIX]"
    exit 1
fi

echo "🚀 Starting complete deployment of Bedrock Agent Test Bed with Knowledge Base..."
if [ -n "$PREFIX" ]; then
    echo "   Resources will be prefixed with: $PREFIX-"
fi
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
echo "🔍 Checking prerequisites..."
if ! command_exists terraform; then
    echo "❌ Error: Terraform is not installed"
    exit 1
fi

if ! command_exists aws; then
    echo "❌ Error: AWS CLI is not installed"
    exit 1
fi

if ! aws sts get-caller-identity >/dev/null 2>&1; then
    echo "❌ Error: AWS CLI is not configured or credentials are invalid"
    exit 1
fi

echo "✅ Prerequisites check passed"
echo ""

# Step 1: Configure terraform.tfvars
echo "⚙️  Step 1: Configuring deployment variables..."
cd terraform
if [ -n "$PREFIX" ]; then
    # Update or create terraform.tfvars with prefix and knowledge base enabled
    if [ -f "terraform.tfvars" ]; then
        # Remove existing prefix and knowledge base lines
        sed -i.bak '/resource_prefix/d' terraform.tfvars
        sed -i.bak '/enable_knowledge_base/d' terraform.tfvars
        rm -f terraform.tfvars.bak
        echo "" >> terraform.tfvars
        echo "# Deployment configuration (auto-generated by deploy-complete.sh)" >> terraform.tfvars
        echo "resource_prefix = \"${PREFIX}\"" >> terraform.tfvars
        echo "enable_knowledge_base = true" >> terraform.tfvars
        echo "   Updated terraform.tfvars with prefix: $PREFIX"
    else
        cat > terraform.tfvars << EOF
# Deployment configuration (auto-generated by deploy-complete.sh)
resource_prefix = "${PREFIX}"
enable_knowledge_base = true
EOF
        echo "   Created terraform.tfvars with prefix: $PREFIX"
    fi
else
    # Enable knowledge base without prefix
    if [ -f "terraform.tfvars" ]; then
        sed -i.bak '/enable_knowledge_base/d' terraform.tfvars
        rm -f terraform.tfvars.bak
        echo "" >> terraform.tfvars
        echo "# Deployment configuration (auto-generated by deploy-complete.sh)" >> terraform.tfvars
        echo "enable_knowledge_base = true" >> terraform.tfvars
        echo "   Updated terraform.tfvars to enable knowledge base"
    else
        cat > terraform.tfvars << EOF
# Deployment configuration (auto-generated by deploy-complete.sh)
enable_knowledge_base = true
EOF
        echo "   Created terraform.tfvars with knowledge base enabled"
    fi
fi
cd ..
echo "✅ Configuration completed"
echo ""

# Step 2: Build Lambda functions
echo "🔨 Step 2: Building Lambda functions..."
./scripts/build.sh

# Move ZIP files to terraform directory
echo "   Moving Lambda packages to terraform directory..."
if [ -f "city_facts_direct.zip" ] && [ -f "city_facts_agent.zip" ]; then
    mv city_facts_direct.zip city_facts_agent.zip terraform/
    echo "✅ Lambda functions built and packaged"
else
    echo "❌ Error: Lambda ZIP files not found after build"
    exit 1
fi
echo ""

# Step 3: Initialize Terraform
echo "📦 Step 3: Initializing Terraform..."
cd terraform
terraform init
cd ..
echo "✅ Terraform initialized"
echo ""

# Step 4: Deploy complete infrastructure
echo "🏗️  Step 4: Deploying complete infrastructure..."
echo "   This will create:"
echo "   - Lambda functions (direct and agent-based)"
echo "   - Bedrock agent with action groups"
echo "   - S3 bucket with knowledge base data"
echo "   - OpenSearch Serverless collection"
echo "   - OpenSearch vector index (automated)"
echo "   - Bedrock knowledge base with data sources"
echo "   - All IAM roles and permissions"
echo ""

cd terraform
terraform apply -auto-approve
cd ..

if [ $? -eq 0 ]; then
    echo "✅ Infrastructure deployment completed successfully"
else
    echo "❌ Infrastructure deployment failed"
    exit 1
fi

echo ""

# Step 5: Display deployment summary
echo "🎉 Deployment Complete!"
echo ""
echo "📋 Summary:"
cd terraform
terraform output | sed 's/^/   /'
cd ..

echo ""
echo "🧪 Test your deployment:"
if [ -n "$PREFIX" ]; then
    echo "   Direct:  aws lambda invoke --function-name ${PREFIX}-bedrock-agent-testbed-city-facts-direct --cli-binary-format raw-in-base64-out --payload '{\"city\": \"Geneva\"}' response.json"
    echo "   Agent:   aws lambda invoke --function-name ${PREFIX}-bedrock-agent-testbed-city-facts-agent --cli-binary-format raw-in-base64-out --payload '{\"city\": \"Berlin\"}' response.json"
else
    echo "   Direct:  aws lambda invoke --function-name bedrock-agent-testbed-city-facts-direct --cli-binary-format raw-in-base64-out --payload '{\"city\": \"Geneva\"}' response.json"
    echo "   Agent:   aws lambda invoke --function-name bedrock-agent-testbed-city-facts-agent --cli-binary-format raw-in-base64-out --payload '{\"city\": \"Berlin\"}' response.json"
fi

echo ""
echo "💡 Next Steps:"
echo "   - Test both Lambda functions with cities that have knowledge base data"
echo "   - Check AWS console to verify all resources are created"
echo "   - Use ./test-lambda.sh for automated testing"
echo "   - Use ./teardown-complete.sh when you're done"

echo ""
echo "🎯 Knowledge Base Data:"
echo "   Your knowledge base contains air quality and cost of living data for 200+ cities"
echo "   Try testing with: Geneva, Berlin, Tokyo, London, Paris, New York, or San Francisco"

# Step 6: Ingest knowledge base data
echo "📊 Step 6: Ingesting knowledge base data..."

# Get IDs from Terraform output
cd terraform
KB_ID=$(terraform output -raw knowledge_base_id)
DS1_ID=$(terraform output -raw air_quality_data_source_id)
DS2_ID=$(terraform output -raw cost_of_living_data_source_id)
cd ..

echo "   Knowledge Base ID: $KB_ID"
echo "   Air Quality Data Source ID: $DS1_ID"
echo "   Cost of Living Data Source ID: $DS2_ID"

# Start first ingestion job
echo "   🔄 Starting air quality data ingestion..."
aws bedrock-agent start-ingestion-job \
  --knowledge-base-id "$KB_ID" \
  --data-source-id "$DS1_ID" \
  --description "Initial ingestion of air quality data" \
  --region us-east-1 > /dev/null

# Wait for first job to complete
echo "   ⏳ Waiting for air quality ingestion to complete..."
while true; do
    STATUS=$(aws bedrock-agent list-ingestion-jobs \
      --knowledge-base-id "$KB_ID" \
      --data-source-id "$DS1_ID" \
      --region us-east-1 \
      --query 'ingestionJobSummaries[0].status' \
      --output text)
    
    if [ "$STATUS" = "COMPLETE" ]; then
        echo "   ✅ Air quality data ingestion completed"
        break
    elif [ "$STATUS" = "FAILED" ]; then
        echo "   ❌ Air quality data ingestion failed"
        exit 1
    fi
    
    sleep 5
done

# Start second ingestion job
echo "   🔄 Starting cost of living data ingestion..."
aws bedrock-agent start-ingestion-job \
  --knowledge-base-id "$KB_ID" \
  --data-source-id "$DS2_ID" \
  --description "Initial ingestion of cost of living data" \
  --region us-east-1 > /dev/null

# Wait for second job to complete
echo "   ⏳ Waiting for cost of living ingestion to complete..."
while true; do
    STATUS=$(aws bedrock-agent list-ingestion-jobs \
      --knowledge-base-id "$KB_ID" \
      --data-source-id "$DS2_ID" \
      --region us-east-1 \
      --query 'ingestionJobSummaries[0].status' \
      --output text)
    
    if [ "$STATUS" = "COMPLETE" ]; then
        echo "   ✅ Cost of living data ingestion completed"
        break
    elif [ "$STATUS" = "FAILED" ]; then
        echo "   ❌ Cost of living data ingestion failed"
        exit 1
    fi
    
    sleep 5
done

echo "✅ All data ingestion completed"
echo ""

# Step 7: Test the deployment
echo "🧪 Step 7: Testing the deployment..."

cd terraform
AGENT_FUNCTION=$(terraform output -raw lambda_function_agent_name)
DIRECT_FUNCTION=$(terraform output -raw lambda_function_direct_name)
cd ..

echo "   Testing direct Lambda function..."
aws lambda invoke \
  --function-name "$DIRECT_FUNCTION" \
  --cli-binary-format raw-in-base64-out \
  --payload '{"city": "Tokyo"}' \
  test_direct_result.json > /dev/null

if [ $? -eq 0 ]; then
    echo "   ✅ Direct Lambda test passed"
else
    echo "   ❌ Direct Lambda test failed"
fi

echo "   Testing agent Lambda function with knowledge base..."
aws lambda invoke \
  --function-name "$AGENT_FUNCTION" \
  --cli-binary-format raw-in-base64-out \
  --payload '{"city": "New York City"}' \
  test_agent_result.json > /dev/null

if [ $? -eq 0 ]; then
    echo "   ✅ Agent Lambda test passed"
else
    echo "   ❌ Agent Lambda test failed"
fi

echo ""
echo "🎉 DEPLOYMENT COMPLETE!"
echo ""
echo "📋 Summary:"
echo "   • Lambda Functions: ✅ Deployed and tested"
echo "   • Bedrock Agent: ✅ Created with action groups"
echo "   • Knowledge Base: ✅ Created with OpenSearch Serverless"
echo "   • Data Sources: ✅ Ingested (air quality + cost of living)"
echo "   • S3 Bucket: ✅ Created and populated"
echo ""
echo "🧪 Test Commands:"
echo "   # Test direct model access:"
echo "   aws lambda invoke --function-name $DIRECT_FUNCTION --cli-binary-format raw-in-base64-out --payload '{\"city\": \"Geneva\"}' response.json"
echo ""
echo "   # Test agent with knowledge base:"
echo "   aws lambda invoke --function-name $AGENT_FUNCTION --cli-binary-format raw-in-base64-out --payload '{\"city\": \"New York City\"}' response.json"
echo ""
echo "   # Use helper scripts:"
echo "   ./scripts/test-lambda.sh both Tokyo"
echo "   ./scripts/dev-workflow.sh test Berlin"
echo ""
echo "📊 Terraform Outputs:"
cd terraform
terraform output
cd ..
echo ""
echo "✨ Your Bedrock Agent Test Bed with Knowledge Base is ready to use!"